on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20.11.0
      - name: Login, build, tag, and push image to Docker Container Registry
        id: build-image
        run: |
          docker login -u fvlvte -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --build-arg="BUILD_TS_ARG=${{ github.event.repository.updated_at }}" -q -t fvlvte/knurobot:latest .
          docker push fvlvte/knurobot:latest
