on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20.11.0
      - name: Login, build, tag, and push image to Docker Container Registry
        id: build-image
        run: |
          docker login -u nginx -p ${{ secrets.DOCKER_PASSWORD }} docker.knur.club
          docker build --build-arg="SECRETS=$(echo -n '${{ secrets.SECRETS }}' | base64)" -t docker.knur.club/backend:latest .
          docker push docker.knur.club/backend:latest
